import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./redux/providers";
import Nav from "../../components/nav";
import ProductModal from "../../components/productModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pay Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <nav className="px-5 py-4">
            <Nav />
          </nav>
          {children}
          <ProductModal />
        </body>
      </html>
    </Providers>
  );
}
